# Generated by Django 4.2.2 on 2023-06-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=200)),
                ('categoria', models.CharField(choices=[('PEITO', 'Peito'), ('COSTAS', 'Costas'), ('BICEPS', 'Biceps'), ('TRICEPS', 'Triceps'), ('PERNAS', 'Pernas')], default='', max_length=100)),
            ],
        ),
    ]
