# Generated by Django 4.2.2 on 2023-06-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_exercicios_publicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicios',
            name='descricao',
            field=models.TextField(max_length=5000),
        ),
    ]
