# Generated by Django 4.2.1 on 2023-07-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_alter_exercicios_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicios',
            name='gif',
            field=models.ImageField(blank=True, upload_to='gifs/%Y/%m/%d/'),
        ),
    ]
