# Generated by Django 4.2.2 on 2023-06-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_alter_exercicios_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicios',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
